version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.go-dev
    working_dir: /app/services/backend
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    tty: true
    command: make run

  postgres:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    environment:
      POSTGRES_DB: vcon
      POSTGRES_USER: vcon
      POSTGRES_PASSWORD: vcon
