version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.go-dev
    working_dir: /app/services/backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: vcon
      DB_USERNAME: vcon
      DB_PASSWORD: vcon
    volumes:
      - .:/app
    ports:
      - "3100:3100"
    depends_on:
      - postgres
    tty: true
    command: make run

  postgres:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    environment:
      POSTGRES_DB: vcon
      POSTGRES_USER: vcon
      POSTGRES_PASSWORD: vcon
