development:
  dialect: postgres
  datasource: host=${DB_HOST} port=${DB_PORT} dbname=${DB_DATABASE} user=${DB_USERNAME} password=${DB_PASSWORD} sslmode=disable
  dir: db/migrations
  table: migrations
